### ISSUE TITLE
[BUG] etcd container in etcd-main-0 pod stucks with OOMKilled status on Azure

### ISSUE THREAD

**Issue by bergerx** [gardener/etcd-backup-restore#115]
**Describe the bug:**
We had etcd OOMKilled in Azure until manually fixed. During the issue the Shoot's apiserver is not accessible due to unhealthy etcd.
Etcd can't recover itselfs unless an operator steps in and manually, our current solution is to manually delete all nodes from Azure Portal.

**Expected behaviour:**
Etcd should auto recover itself from such issues.

**How To Reproduce (as minimally and precisely as possible):**
We can't reliably reproduce the issue, but it sporadically happened on several Shoot's Etcds.

**Logs:**
Unfortunately logs are rotated and not available anymore, we have logs in ElasticSearch and logs are not easy to extract from there without losing the order (ES keeps logs with timestamps in ms resolution, so any logs omitted in same ms wont be in correct ordered). I tried to go over the logs below in the timeline.

**Screenshots (if applicable):**
The status of the etcd-main-0 Pod shows that the etcd container is OOMKilled (not the backup-restore container)
![image](https://user-images.githubusercontent.com/45531/52536157-aaef0180-2d4e-11e9-8c3a-ac4a54373b63.png)

Screenshot of same issue happened twice on a Shoot within a day.
![image](https://user-images.githubusercontent.com/45531/52536335-07532080-2d51-11e9-81f9-34b0d567a009.png)

**Environment (please complete the following information):**
 - Etcd version/commit ID : v3.3.10
 - Etcd-backup-restore version/commit ID: 0.4.1
 - Cloud Provider [All/AWS/GCS/ABS/Swift]: Azure
 - Seed is running on AKS service with Kubernetes version: 1.11.5
 - Etcd PV in use: Azure 256 GiB (Premium SSD) (IOPS limit=1100, Throughput limit (MB/s)=125)
 - Some scaling info about the shoot cluster: nodes:10, pods:217, deploy:83, rs:286, sts:13, ds:6 (no dramatic change on the workload for a while other then regular ongoing deployment rollouts)

Regular apiserver load before apiserver
![image](https://user-images.githubusercontent.com/45531/52539330-da186980-2d74-11e9-9642-b5a3642057ad.png)

Amount of resources in use:
![image](https://user-images.githubusercontent.com/45531/52539781-fff43d00-2d79-11e9-9f8f-a271d0d16123.png)

**Anything else we need to know?**:

Although the pod's status field reports the etcd container is OOMKilled, we can't see an increase in the etcd container's memory in any prometheus metrics. According to the memory usage reported from the etcd container, even the maximum reported level is safe to be not OOM Killed. This tells us the memory usage of the container jumps to a level that more than the container's limit all of a sudden and the container get killed immediately, metrics system never have a chance to catch the elevated memory usage of the container due to 15s scrape interval.

We reported issue in Slack previously:
* https://kubernetes.slack.com/archives/CB57N0BFG/p1549567889627400
* https://kubernetes.slack.com/archives/CB57N0BFG/p1549637745654700

Used Kibana queries during investigation:

```
event.involvedObject.namespace.keyword:"shoot--flow--flow" AND event.involvedObject.name.keyword:"etcd-main-0"
kubernetes.namespace_name.keyword:"shoot--flow--flow" AND kubernetes.pod_name.keyword:"etcd-main-0"
```

**Timeline**:
Timeline of the last occurance (all times are UTC):

```
2019-02-08

recent events on etcd and backup-restore containers
17:17:41  etcd container started and finished compaction
17:19:11  backup-restore container started delta snapshot, msg="Taking delta snapshot for time: 2019-02-08 17:19:11.936458854 +0000 UTC"
17:19:12  backup-restore container completed an delta snapshot (next log from backup-restore is when etcd container is restarted): msg="Successfully saved delta snapshot at: Backup-1549584000/Incr-18756018-18757064-1549646351"
17:21:13  etcd container: mvcc: finished scheduled compaction at 18756449 (took 2.546498ms)

seemingly related signs, "took too long" messages can also be considered usual
17:22:26  etcd "took too long" event spike starts (from this time there are 66 logs in 3 seconds)
17:22:30  last healthy etcd memory datapoint values reported in Prometheus (req: 500MB, usage: 1.23GB, limit: 2.5GB, etcd process_resident_memory_bytes: 1.020GB)
17:22:34  last log line from etcd container: "W | etcdserver: read-only range request "key:"/registry/configmaps/kube-system/" range_end:"/registry/configmaps/kube-system0" " with result "range_response_count:736 size:32098389" took too long (124.058866ms) to execute"

problem starts here
17:22:35  etcd container "Created container" event (pod.status field indicates etcd container is terminated as a result of OOMKilled), first reported event from this pod for a long time
17:22:36  backup-restore: level=info msg="Received start initialization request."
17:22:51  etcd container "Unhealthy", Readiness probe failed: HTTP probe failed with statuscode: 503
17:22:53  backup-restore container "Started container" event
17:22:56  etcd container "Unhealthy", Readiness probe failed: HTTP probe failed with statuscode: 503
17:23:01  etcd container "Unhealthy", Readiness probe failed: HTTP probe failed with statuscode: 503
17:34:48  etcd and backup-restore container "Created container"
17:44:57  etcd container "BackOff", Back-off restarting failed container

... problem persists (etcd container is unhealthy and in BackOff) until manual fix is applied
```

**Investigation and mitigation attempts**:

Here are the things we tried, but none helped so far:
* delete PV along with etcd-main-0 pod and let whole data to be restored by backup-restore
* disable GCM reconciliation and modify resources and limits of etcd pod/containers, we even tried with 16GB of mem and still got OOM kill for etcd container
* replace the PV with faster SSD disk to eliminate the disk iops issue (current PV in use is Azure 256 GiB (Premium SSD) (IOPS limit=1100, Throughput limit (MB/s)=125))
* tried to distribute etcd-main-0 pods among nodes manually, if it could be a network bottleneck for remotely attached disks (edited) 

**Workaround**:
Manually delete all VMs from Azure Portal, and next time etcd starts if doesn't fail.

**Comment by amshuman-kr** [comment]
@bergerx Thanks for opening issue. The information here will help us.

I have one question about the DB size is shown as ~190MiB whereas the Volume used Bytes is ~1.5GiB. Can you help me understand that difference?

We have seen these kind issues before when the data size grows to 1.5 to 2GiB but not for data sizes around 200MiB.

**Comment by fsniper** [comment]
We are running https://github.com/gardener/etcd-backup-restore as a sidecar in our etcd deployment. So the extra disk is used by etcd-backup-restore. 

Disk usage is as follows:

```
/ # du -d3 -h  /var/etcd/data
16.0K	/var/etcd/data/lost+found
427.3M	/var/etcd/data/new.etcd/member/wal
181.6M	/var/etcd/data/new.etcd/member/snap
608.9M	/var/etcd/data/new.etcd/member
608.9M	/var/etcd/data/new.etcd
844.9M	/var/etcd/data/temp
1.4G	/var/etcd/data
```

**Comment by fsniper** [comment]
temp directory:
```
/ # ls -lh /var/etcd/data/temp/
total 865192
-rw-------    1 root     root      177.4M Feb  6 00:00 etcd-backup-107990644
-rw-------    1 root     root      175.8M Jan 17 00:00 etcd-backup-173257644
-rw-------    1 root     root      180.0M Jan 31 00:00 etcd-backup-283384433
-rw-------    1 root     root      178.6M Feb  2 00:00 etcd-backup-624015425
-rw-------    1 root     root      100.3M Feb 10 00:00 etcd-backup-916712150
-rw-------    1 root     root       32.8M Feb  8 17:22 etcd-backup-989989503
```

**Comment by swapnilgm** [comment]
Just FYI, I was referring to issue https://github.com/grpc/grpc-go/issues/2444 in slack conversation. Not sure weather this has to do something with this, But I will just cross check, if it is happening with configuration for etcd deployed by gardener. And is there possibility for some data intensive workload (like large configmaps or secrets) causing such etcd leak memory and get OOM killed.

**Comment by swapnilgm** [comment]
Thanks @fsniper for the details, looks like temporary files created by backup-restrore  sidecar are not cleared, probably in case of restart. I'll cross check that part as well.

**Comment by fsniper** [comment]
@swapnilgm I can't see any "grpc: received message larger than max" errors in our logs. I am not sure if this eliminates the aforemantioned grpc bug.

**Comment by swapnilgm** [comment]
Ah ok. Thanks for info.  I'll take that in consideration.

**Comment by praveendhac** [comment]
Saw the issue again, there was no workload on shoots.

**Comment by amshuman-kr** [comment]
@praveendhac Could you please share some more information about your error scenario? For example, was there workload before on this shoot. The memory issue during database verification could be still in effect even if there is no workload at the moment.

**Comment by amshuman-kr** [comment]
The grpc-go issue seems to have been [fixed](https://github.com/grpc/grpc-go/issues/2444#issuecomment-462575474) yesterday.

**Comment by bergerx** [comment]
I'm not sure that bug is the one that's effecting us. In our env, none of the instances of our problem had a slowly increasing memory on etcd container before getting OOMKilled. So our pattern doesnt seem to match the one reported in that issue.

We actually never be able to catch a metric data point that shows increased etcd container memory, we only see that the container is reported to be terminated with an "OOMKilled" status in the Pod's stats field. Based on the fact that we have no datapoints in our metrics system I assume it must be a sudden (faster than our metric collection interval) memory increase that'd cause the issue.

Now i see that we need to verify the Kernel logs that the reported OOMKilled reflects the reality or not.

I also dont know how the cgroup memory implementation accounts memory and triggers the OOM killer for the related cgroup.

**Comment by bergerx** [comment]
From: @amshuman-kr
> The memory issue during database verification could be still in effect even if there is no workload at the moment.

For this one, i checked the log on a recent one and wasn't able to see a correlation you can see all related logs in the timeline in the description of this issue, they doesnt seem to corelate. But now i guess we have a broken test cluster that we didnt fix yet, maybe we @praveendhac can share the logs of both etcd and backup-restore container at the time when this problem happens.

**Comment by bergerx** [comment]
from @swapnilgm :
> And is there possibility for some data intensive workload (like large configmaps or secrets) causing such etcd leak memory and get OOM killed.

I was cheking the previous conversations and this one just caught my attention, and actually we could have pretty big ConfigMaps. I guess we have Grafana dashboards in ConfigMaps and they could be be big, I don't have access to my computer now, but I'll check this shortly. Even if this is the this still doesnt tell why deleting nodes is helping, but could give use some clue for the actual problem. I'll try to check the sizes of configmaps and secrets in the cluster.

**Comment by praveendhac** [comment]
@amshuman-kr We hit the issue of `etcd OOMKilled` on a idle cluster with no workload, when etcd recovers API server pod goes into `CrashLoopBackoff` state. When API server pod is deleted `etcd-main` crashes with OOMKilled, before crash I am seeing lots of range requests for keys around ~20MB in size (may be large Configmaps). 

As per https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/limit.md max request size limit is 1MB but we see range requests of size 25MB sometimes.  
```
2019-02-12 17:21:30.448349 W | etcdserver: read-only range request "key:\"/registry/configmaps/kube-system/\" range_end:\"/registry/configmaps/kube-system0\" " with result "range_response_count:374 size:25260832" took too long (1.611140449s) to execute
2019-02-12 17:21:30.454819 W | etcdserver: read-only range request "key:\"/registry/configmaps/kube-system/\" range_end:\"/registry/configmaps/kube-system0\" " with result "range_response_count:374 size:25260832" took too long (1.617534726s) to execute
```

**Comment by amshuman-kr** [comment]
The fix for #102 in #116 might have an implication here too. See [here](https://github.com/gardener/etcd-backup-restore/issues/102#issuecomment-463679537).

The issue there was that the watchers for the delta snapshots were not closed properly which resulted in the watches and the `grpc` streams to be not cleaned up. This might potentially have an impact on the `etcd` container as well because of the spurious watches.

**Comment by bergerx** [comment]
This issue seems to be resolved by itself, which makes me nervous.
This issue was happening occasionally on different Gardener installations and can be happening in any shoot (was more likely to be hit on busy cluster with many control plane operations).
We didn't do any updates on Gardener (so no updates on etdc-backup-restore) in last 2 months and our workload is pretty much the same. But this issue has not been happening anymore.

I'm closing this issue since we didn't see it again in last 2 months. @swapnilgm and @amshuman-kr thanks for all the help on identifying the root cause and troubleshooting .

**Comment by majst01** [comment]
Hi,
sadly this happens in our soil cluster out of the dark without any changes to etc-backup-restore for 2 month.
This is  in our test soil with very low resources managed by gardener and with no significant changes in the usage as far as we can tell.

Our version of etcd-backup-restore is v0.9.1

**Comment by amshuman-kr** [comment]
@majst01 That is unfortunate. Would you have some details such as the CPU and memory consumption for the etcd and the backup-restore container ~30m before this happened?
