### ISSUE TITLE
VPA for etcd backup and restore

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#129]
# Story
As an administrator, I would like to use the recommendations of VPA to scale ETCD to be able to manage larger Kubernetes Clusters

# Acceptance Criteria
- [ ] Observe the recommendations from VPA to scale ETCD and side car components
- [ ] Integrate relevant recommendations into ETCD and side car components

**Comment by swapnilgm** [comment]
This feature is implemented in https://github.com/gardener/gardener/pull/1421
