### ISSUE TITLE
Change the operation mode of VPA for etcd-backup-restore

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#145]
# Task
Based on the observations of the VPA-exporter [recommendations for VPA], switch the operation mode of the VPA to initial 

# Acceptance Criteria
- [ ] Use the recommendations of VPA for etcd-backup-restore and scale accordingly

**Comment by swapnilgm** [comment]
This is feature is implemented ini https://github.com/gardener/gardener/pull/1421
