### ISSUE TITLE
[Improvement] Prevent eviction of etcd during scaling by Cluster Autoscaler 

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#147]
# Improvement
Prevent eviction of etcd during scaling by Cluster Autoscaler 

# Acceptance Criteria
- [ ] CA to ignore nodes with etcd during downscale

**Comment by vlerenc** [comment]
The annotation `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` should prevent CA to downscale nodes with ETCDs (according to the CA docs).

**Comment by shreyas-s-rao** [comment]
Closing this issue via https://github.com/gardener/gardener/pull/937
