### ISSUE TITLE
[BUG] Possibility of seg fault at type assertion.

### ISSUE THREAD

**Issue by georgekuruvillak** [gardener/etcd-backup-restore#163]
**Describe the bug:**
There is a possibility of a seg fault [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/abs_snapstore.go#L85) if the type assertion of `err` to `azblob.StorageError` failed [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/abs_snapstore.go#L83). Calling `aer.Error()` would fail if `aer` is `nil`.

**Expected behaviour:**

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by swapnilgm** [comment]
Fixed via #164
