### ISSUE TITLE
[Feature] Add options for etcd username and password

### ISSUE THREAD

**Issue by ae6rt** [gardener/etcd-backup-restore#169]
**Feature:**

etcd can be secured with a username and password.  It would be helpful if `etcd-backup-restore` would support this.

**Motivation:**

Production clusters may be secured with username and password.  The backup tool must handle this use case.

**Approach/Hint to the implement solution:**

Add username and password command line options, and flow them into the underlying etcd clientv3 config.

**Comment by shreyas-s-rao** [comment]
Closing via https://github.com/gardener/etcd-backup-restore/pull/170
