### ISSUE TITLE
Incremental/Continuous ETCD Backups

### ISSUE THREAD

**Issue by vlerenc** [gardener/etcd-backup-restore#2]
# Story
- As user I want my Kubernetes cluster always to show my latest state and not "forget" resources.
- As provider I want etcd backups to be written incrementally/continuously (with full backups now and then) so that I run a near-zero risk of infrastructure inconsistencies after backup.

# Motivation
In order to make sure our ETCD backups are as fresh as possible and reflect the actual infrastructure state as good as possible, we should continue the begun work with the incremental/continuous backups.

# Acceptance Criteria
- [x] ETCD full backups are taken regularly, e.g. every hour
- [x] Logs of ETCD watches are written continuously
- [x] Logs taken before a new ETCD full backup are deleted
- [x] When a restore is necessary the last ETCD full backup plus the additional ETCD logs (from the last entry in the full backup) are restored automatically

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by swapnilgm** [comment]
Feature added in #29
