### ISSUE TITLE
[Feature] REST apis to return the details of the snapshot taken.

### ISSUE THREAD

**Issue by georgekuruvillak** [gardener/etcd-backup-restore#213]
**Feature (What you would like to be added):**
REST apis should be changed in backup-restore to return information about the snapshot taken in addition to the status. Also would be nice to have an api that lists the list of snapshots from the latest full and the subsequent deltas. 
**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**

**Comment by swapnilgm** [comment]
Ref: https://github.com/gardener/etcd-druid/issues/17
