### ISSUE TITLE
[BUG] Individual chunks of multipart upload are still present after upload has been completed

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#268]
**Describe the bug:**
The current chunked backup upload implementation relies on the storage provider to clean up the individual chunks after the upload has been completed. S3 does this [automatically](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html). But GCS [doesn't](https://cloud.google.com/storage/docs/composite-objects#composing). This means that the chunks remain in GCS and eat up space. This might be true in other storage providers.

Credit: @majst01

**Expected behavior:**
Individual chunks should be deleted after the chunked upload has been completed either by the storage provider or by `etcd-backup-restore`.

**How To Reproduce (as minimally and precisely as possible):**
Use GCS as the storage provider.

**Logs:**

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/32157254/95174455-b7538800-07d7-11eb-8860-18894c60e384.png)

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by shreyas-s-rao** [comment]
Also refer [here](https://cloud.google.com/storage/docs/composite-objects#uploads).
