### ISSUE TITLE
[Feature]Backup to MinIO / other private S3 

### ISSUE THREAD

**Issue by neotkm** [gardener/etcd-backup-restore#288]
**Feature (What you would like to be added):**
Backup etcd to alternative S3. For example, to a private MinIO.

**Motivation (Why is this needed?):**
Corporate policies do not allow data to be stored outside of the infrastructure.

**Approach/Hint to the implement solution (optional):**
Add an option / environment variable --endpoint-url to specify the private S3 address

**Comment by amshuman-kr** [comment]
Thanks for the feature request, @neotkm. The #261 which added support for OCS S3 object store includes a mechanism to configure a different endpoint URL. Would this suffice or do you require any further changes?

**Comment by neotkm** [comment]
OCS S3 solves my problem.
Thanks for your help.
