### ISSUE TITLE
[Feature] Enhance initialisation sequence according to the multi-node ETCD proposal

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#322]
**Feature (What you would like to be added):**

Enhance [initialisation sequence](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#decision-table-for-etcd-backup-restore-during-initialization) according to the multi-node ETCD proposal.

This should including the following broad topics.
1. Loading template etcd configuration (supplied by `etcd-druid`).
2. Reading `Status` from the correspoding `Etcd` resource.
3. [Membership](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#how-to-detect-if-valid-metadata-exists-in-an-etcd-member) and [data verification](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#how-to-detect-if-valid-data-exists-in-an-etcd-member)
4. If necessary, removing old member and adding a new member 
5. If necessary, restoring from latest full snapshot
6. If necessary, applying incremental snapshots
7. If necessary, uploading a fresh snapshot (full or incremental)
8. If necessary, generate fresh tailored etcd configuration for the corresponding member based on the supplied template configuration and other information from steps above so that the configuration can be used by the etcd container of the same member pod.

**Motivation (Why is this needed?):**

Pick individually executable pieces of the [multi-node proposal](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md).

**Approach/Hint to the implement solution (optional):**

**Comment by ishan16696** [comment]
Closing this issue in favour of these PRs: https://github.com/gardener/etcd-backup-restore/pull/419 ,https://github.com/gardener/etcd-custom-image/pull/8, https://github.com/gardener/etcd-druid/pull/193

/close
