### ISSUE TITLE
Extended Shoot Cluster Control Plane Backup & Restore

### ISSUE THREAD

**Issue by vlerenc** [gardener/etcd-backup-restore#34]
In context of the Gardener ring and the seed cluster disaster recovery, @rfranzke and @vlerenc raise the question, whether the current solution can be extended to also include the seed cluster resources for a shoot cluster, a.k.a. "moving control planes", please see https://github.com/amshuman-kr/gardener/blob/master/docs/proposals/shoot-control-plane-migration/README.md.

**Comment by vlerenc** [comment]
Thank you! Let me keep the ticket please open for a while until the discussion above comes to an end and then we'll move the ticket accordingly.

**Comment by bergerx** [comment]
Related wip design doc dicsussions: [WIP] Design proposal for shoot control-plane migration gardener/gardener#204

**Comment by vlerenc** [comment]
Closing this ticket as Gardener extensibility https://github.com/gardener/gardener/pull/370 will make control plane migration simpler and implicitly deal with extended seed state (https://github.com/gardener/gardener/pull/204 was closed for the same reason).
