### ISSUE TITLE
Compression Failed in ETCD Druid Job with larger DB Size

### ISSUE THREAD

**Issue by Harisrini2020** [gardener/etcd-backup-restore#360]
**Describe the bug:**
We are trying the ETCD Druid Job for snapshot compaction with 200 Delta Snapshots. Druid job fetching the snapshots and compacting successfully but compression failed.Also the full snapshot is uploaded without compression in compressed format.So , while restoring the snapshots, we are getting error with wrong form of data.

**Expected behavior:**
Compression should be successfull.

**How To Reproduce (as minimally and precisely as possible):**
200 Delta Snapshot of data with each 10MB Size.
Total DB Size of ETCD = ~2.9GB
Total Keys Stored in ETCD = ~44,000
Each Value Size = ~53Kb

1. Loaded 200 Snapshots 
2. Compact snapshots using ETCD Druid Job.

**Logs:**
`time="2021-07-26T11:34:45Z" level=info msg="Finished defragmenting etcd member[127.0.0.1:35425]"
time="2021-07-26T11:34:45Z" level=info msg="Probable DB size change for etcd member [127.0.0.1:35425]:  2516856832B -> 2378665984B after defragmentation"
{"level":"warn","ts":"2021-07-26T11:34:45.248Z","caller":"clientv3/retry_interceptor.go:116","msg":"retry stream intercept"}
time="2021-07-26T11:34:45Z" level=info msg="start compressing the snapshot using gzip Compression Policy" actor=compressor
time="2021-07-26T11:34:45Z" level=info msg="Successfully opened snapshot reader on etcd"
{"level":"info","ts":"2021-07-26T11:34:45.839Z","caller":"mvcc/kvstore_compaction.go:55","msg":"finished scheduled compaction","compact-revision":43999,"took":"20.891745226s"}
time="2021-07-26T11:35:15Z" level=error msg="compression failed: context deadline exceeded" actor=compressor
time="2021-07-26T11:35:15Z" level=info msg="Successfully initiated the multipart upload with upload ID : r0AKDE1R0E7SoyFFlixUMtQi7uBHWWR9D6MxTPW9VB8y9US1YkGcUk7HxWEGN6YCizni0S_.8Z_6pfuoiKCKerHMfEzIrbFHXs5lf1D3QvRMvZ.6xc0LqFNTkt7F6vqZ"
time="2021-07-26T11:35:15Z" level=info msg="Uploading snapshot of size: 409255487, chunkSize: 5242880, noOfChunks: 79"
time="2021-07-26T11:35:15Z" level=info msg="Triggered chunk upload for all chunks, total: 79"
time="2021-07-26T11:35:15Z" level=info msg="No of Chunks:= 79"
time="2021-07-26T11:35:15Z" level=info msg="Uploading chunk with id: 1, offset: 0, attempt: 0"
time="2021-07-26T11:35:15Z" level=info msg="Uploading chunk with id: 2, offset: 5242880, attempt: 0"
time="2021-07-26T11:35:15Z" level=info msg="Uploading chunk with id: 4, offset: 15728640, attempt: 0"
time="2021-07-26T11:35:15Z" level=info msg="Uploading chunk with id: 3, offset: 10485760, attempt: 0"
time="2021-07-26T11:35:15Z" level=info msg="Uploading chunk with id: 5, offset: 20971520, attempt: 0"
time="2021-07-26T11:35:17Z" level=info msg="Uploading chunk with id: 6, offset: 26214400, attempt: 0"
time="2021-07-26T11:35:17Z" level=info msg="Received chunk result for id: 1, offset: 0"
`

**Environment (please complete the following information):**
ETCD Image: v3.4.13-bootstrap-dev-1 
BR Image: v0.12.1

**Comment by ishan16696** [comment]
`time="2021-07-26T11:35:15Z" level=error msg="compression failed: context deadline exceeded"`
Compression of snapshot is failed [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/compressor/compressor.go#L59-L62) . I think it is because `io.Copy()` has failed.

**Comment by ishan16696** [comment]
[save()](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/abs_snapstore.go#L148-L163) function call  also uses `io.Copy()`  internally before chunking the snapshot.

**Comment by ishan16696** [comment]
As the Error message says ` context deadline exceeded` and AFIK[ io.Copy](https://cs.opensource.google/go/go/+/go1.16.6:src/io/io.go;l=381) don't use any context. Then I think it is the context that was passed to take the snapshot.

**Comment by amshuman-kr** [comment]
The problem is that the context passed to [client.Snapshot(ctx)](https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/etcdutil/etcdutil.go#L123) is what timed out.

The problem is that connection timeout is being used as the [context timeout for the full snapshot](https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/snapshot/snapshotter/snapshotter.go#L293). This is clearly too short for large snapshots. 

We should use a specific larger timeout for the context for full snapshot.

**Comment by ishan16696** [comment]
I think we have to use large timeout for `context` whenever `backup-restore` will take/trigger the fullSnapshot and Moreover we also have to use the large timeout for restoration as decompression  of large baseSnashot can also be longer.
Do I miss any case @amshuman-kr @shreyas-s-rao where time out can occur ?

**Comment by shreyas-s-rao** [comment]
@ishan16696 During restoration, context is mainly used for applying the events from delta snapshots to the etcd, in addition to empty get calls to etcd to get the latest revision. Few cloud-specific snapstore implementations of `Fetch` function use a [context.Background()](https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/snapstore/abs_snapstore.go#L107) or [context.TODO()](https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/snapstore/gcs_snapstore.go#L78) to fetch the object from the bucket.
For snapshotting, looks like full snapshots is where we need a longer context, as you've found.

**Comment by ishan16696** [comment]
yes @shreyas-s-rao, thanks for confirming  I found out that [defragmentation](https://github.com/ishan16696/etcd-backup-restore/blob/master/pkg/defragmentor/defrag.go#L54) might need this `LongerConnectionTimeout` but I have already handled those cases of defragmentation in [LeaderElection PR](https://github.com/gardener/etcd-backup-restore/pull/353)
