### ISSUE TITLE
Defragmentation Failed in ETCD Druid Job

### ISSUE THREAD

**Issue by Harisrini2020** [gardener/etcd-backup-restore#366]
**Describe the bug:**
We are trying the ETCD Druid Job for snapshot compaction with 200 Delta Snapshots. Druid job fetching the snapshots successfully but defragmentaion is failed.

`time="2021-08-02T08:23:18Z" level=error msg="Failed to defragment etcd member[127.0.0.1:35443] with error: context deadline exceeded"
time="2021-08-02T08:23:18Z" level=error msg="failed to defragment: context deadline exceeded"`

**Expected behavior:**
time="2021-08-02T08:02:03Z" level=info msg="Finished defragmenting etcd member[127.0.0.1:40981]"

**How To Reproduce (as minimally and precisely as possible):**
200 Delta Snapshot of data with each 10MB Size.
Total DB Size of ETCD = ~2.9GB
Total Keys Stored in ETCD = ~44,000
Each Value Size = ~53Kb

Loaded 200 Snapshots using ETCDCTL Tool.
Created the ETCD Druid Job.

**Logs:**
`{"level":"info","ts":"2021-08-02T07:45:37.535Z","caller":"wal/wal.go:693","msg":"created a new WAL segment","path":"/tmp/compactor-923578050/member/wal/0000000000000025-000000000000aab6.wal"}
time="2021-08-02T07:45:37Z" level=info msg="Applying delta snapshot Incr-00043801-00044000-1627297345.gz" actor=restorer
time="2021-08-02T07:45:38Z" level=info msg="Cleanup complete" actor=restorer
time="2021-08-02T07:45:38Z" level=info msg="Restoration complete." actor=restorer
time="2021-08-02T07:45:38Z" level=info msg="Restoration for compaction is over"
{"level":"info","ts":"2021-08-02T07:45:38.356Z","caller":"mvcc/index.go:189","msg":"compact tree index","revision":44000}
time="2021-08-02T07:45:38Z" level=info msg="Defragmenting etcd member[127.0.0.1:35883]"
{"level":"info","ts":"2021-08-02T07:45:38.366Z","caller":"v3rpc/maintenance.go:80","msg":"starting defragment"}
{"level":"info","ts":"2021-08-02T07:45:38.646Z","caller":"backend/backend.go:381","msg":"defragmenting","path":"/tmp/compactor-923578050/member/snap/db","current-db-size-bytes":2517856256,"current-db-size":"2.5 GB","current-db-size-in-use-bytes":2433822720,"current-db-size-in-use":"2.4 GB"}
{"level":"warn","ts":"2021-08-02T07:46:08.366Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///127.0.0.1:35883","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
time="2021-08-02T07:46:08Z" level=error msg="Failed to defragment etcd member[127.0.0.1:35883] with error: context deadline exceeded"
time="2021-08-02T07:46:08Z" level=error msg="failed to defragment: context deadline exceeded"
{"level":"warn","ts":"2021-08-02T07:46:08.366Z","caller":"clientv3/retry_interceptor.go:116","msg":"retry stream intercept"}
time="2021-08-02T07:46:08Z" level=info msg="start compressing the snapshot using gzip Compression Policy" actor=compressor
time="2021-08-02T07:46:08Z" level=info msg="Successfully opened snapshot reader on etcd"
{"level":"info","ts":"2021-08-02T07:48:21.327Z","caller":"backend/backend.go:446","msg":"defragmented","path":"/tmp/compactor-923578050/member/snap/db","current-db-size-bytes-diff":-139132928,"current-db-size-bytes":2378723328,"current-db-size":"2.4 GB","current-db-size-in-use-bytes-diff":-55332864,"current-db-size-in-use-bytes":2378489856,"current-db-size-in-use":"2.4 GB","took":"2m42.960257144s"}
{"level":"info","ts":"2021-08-02T07:48:21.327Z","caller":"v3rpc/maintenance.go:94","msg":"finished defragment"}
{"level":"info","ts":"2021-08-02T07:48:21.918Z","caller":"mvcc/kvstore_compaction.go:55","msg":"finished scheduled compaction","compact-revision":44000,"took":"2m43.553007318s"}
{"level":"warn","ts":"2021-08-02T07:48:51.333Z","caller":"backend/backend.go:253","msg":"snapshotting taking too long to transfer","taking":"30.000110635s","bytes":2378723328,"size":"2.4 GB"}
{"level":"warn","ts":"2021-08-02T07:49:21.333Z","caller":"backend/backend.go:253","msg":"snapshotting taking too long to transfer","taking":"1m0.000241867s","bytes":2378723328,"size":"2.4 GB"}
{"level":"warn","ts":"2021-08-02T07:49:51.333Z","caller":"backend/backend.go:253","msg":"snapshotting taking too long to transfer","taking":"1m30.000044768s","bytes":2378723328,"size":"2.4 GB"}
{"level":"warn","ts":"2021-08-02T07:50:21.333Z","caller":"backend/backend.go:253","msg":"snapshotting taking too long to transfer","taking":"2m0.000065149s","bytes":2378723328,"size":"2.4 GB"}
time="2021-08-02T07:50:27Z" level=info msg="Total written bytes: 2378723360" actor=compressor
`

**Environment (please complete the following information):**
ETCD Image: v3.4.13-bootstrap-dev-1
BR Image: eu.gcr.io/gardener-project/gardener/etcdbrctl:v0.13.0-dev-13e83575aa3030157d7b93021dd334f8a69b0974

**Comment by shreyas-s-rao** [comment]
The error stems from https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/compactor/compactor.go#L123 which is caused due to a short default timeout for defragmentation [here](https://github.com/gardener/etcd-backup-restore/blob/1638bef219bef7c5367875d78f8cd6a83ca5c539/pkg/etcdutil/types.go#L27), from which `defragCtx` is created. We will either have to increase the default timeout or introduce a configurable flag like `--etcd-defrag-timeout` to specify a larger timeout.
/cc @abdasgupta

**Comment by ishan16696** [comment]
I was expecting this and already pointed out this here too. https://github.com/gardener/etcd-backup-restore/issues/360#issuecomment-887460152

**Comment by ishan16696** [comment]
> We will either have to increase the default timeout or introduce a configurable flag like --etcd-defrag-timeout to specify a larger timeout

Can't we just rename this `--etcd-snapshot-timeout`  which is added in this [PR](https://github.com/gardener/etcd-backup-restore/pull/361) to somethings general which we can use [here](https://github.com/ishan16696/etcd-backup-restore/blob/master/pkg/defragmentor/defrag.go#L54) too.

**Comment by amshuman-kr** [comment]
> Can't we just rename this --etcd-snapshot-timeout which is added in this PR to somethings general and re-use it instead of adding a new flag ,which we can also be used here too. WDYT ?

I would prefer a different flag like `--etcd-defrag-timeout`. It is not clear to me if we need exactly the same timeout values for both.
