### ISSUE TITLE
Optimise the restoration process

### ISSUE THREAD

**Issue by swapnilgm** [gardener/etcd-backup-restore#41]
Currently, while restoring etcd from available incremental/delta snapshots, it fetch the snapshot and applies the snapshot sequentially one by one. For reducing the snapshot fetch time from object store, we can parallelise the fetch call. This can be done at two level: 
Lets we have delta snapshot in order as A, B, C ... then
- Once A is fetched, one go routine will start unmarsheling and applying events from it to embedded etcd and simultaneously another go routine will start fetching next delta snapshot i.e. B. We can think of it as kind of two step pipeline parallelism implementation.
- Another way is trigger fetch call for all (i.e. A,B as well as C) the snapshots in parallel initially itself. And apply the sequentially to embedded etcd.

cc: @georgekuruvillak @amshuman-kr

**Comment by vlerenc** [comment]
It will be interesting to see how long restore/recovery for large/busy etcds will take. At one point in time, we will need backup & restore/recovery tests as part of the landscape validation pipelines (simply also because landscape misconfiguration could break the functionality).

**Comment by amshuman-kr** [comment]
A small variation can be that, there can be a one *downloader* goroutine which keeps downloading files and there is another *applier* goroutine which keeps applying the events from the files sequentially. The *downloader* send an event (via a channel) to the *applier* to co-ordinate between them.

This way, the *downloader* becomes relatively independent of the *applier*.
