### ISSUE TITLE
Configure custom S3 endpoint

### ISSUE THREAD

**Issue by lechugaletal** [gardener/etcd-backup-restore#416]
Hi, 
Is there a way to configure etcdbrctl with a custom **S3 endpoint** for snapshot/backup storage? 

I understand that the chosen path is to configure the AWS S3 auth keys and let it connect to your bucket, I'm struggling into connecting the backup utility to a custom s3/minio storage because there is no option to configure the endpoint via [ ~/.aws/credentials ] nor [ ~/.aws/conf ]. 

AWS cli allows you to set the **--endpoint-url** flag with a custom endpoint of your own, p.e.:
`aws --endpoint-url https://my.full.domain:9000 s3 mb s3://dummybucket`

..but there is no option to bypass the etcdbrctl tool and add this flag.

Greets and many thanks in advance!

**Comment by ishan16696** [comment]
Hi @lechugaletal ,

Right now we don’t support MinIO S3 object store and we haven’t exposed the custom URL field. 
Unfortunately we all are busy with some other important features like [Multi-node backup-restore](https://github.com/gardener/etcd-druid/issues/107), feel free to implement this feature, and you can take a reference of this PR #261 which added support for OCS S3 object store
