### ISSUE TITLE
[Feature] Dynamically load IaaS credentials during runtime

### ISSUE THREAD

**Issue by timuthy** [gardener/etcd-backup-restore#422]
**Feature (What you would like to be added):**
The etcd-backup-restore process reads IaaS credentials for access cloud provider storage when it creates the [Snapstore](https://github.com/gardener/etcd-backup-restore/blob/322d3c74fcd5ea7be9961ce5e9d7ffed48ecc34e/pkg/snapstore/utils.go#L73). Most of the times the credentials change, e.g. due to secret rotation, the process needs to be restarted (depending on Snapstore provider).

To circumvent a required restart, etcd-backup-restore should re-read the credentials every time it performs any action on the bucket.

**Motivation (Why is this needed?):**
Dynamic credential retrieval prevents avoidable pod/container restarts which always involves a downtime of the etcd cluster if only one replica is involved.

**Approach/Hint to the implement solution (optional):**
It's important to use a file-based approach for every supported provider (already true for GCP today) rather than storing the access information in env vars. `etcd-backup-restore` is mostly deployed as a sidecar and content refreshing is only supported if Kubernetes secrets are mounted into the container (see https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically).

**Comment by ishan16696** [comment]
> etcd-backup-restore should re-read the credentials every time it performs any action on the bucket.

To do this there is no other option but to create/update the [snapstore object](https://github.com/gardener/etcd-backup-restore/blob/322d3c74fcd5ea7be9961ce5e9d7ffed48ecc34e/pkg/snapstore/utils.go#L38) every time `backup sidecar` tries to take the snapshot(full or delta).

**Comment by ishan16696** [comment]
**To Dynamically load IaaS credentials during runtime:**

- [ ] To circumvent a required restart, `etcd-backup-restore` should recreate/update the snapstore object  every time it performs any action on the bucket.
- [ ] Mount Kubernetes secrets into the container:
  - [ ] Google cloud storage(GCS)
  - [ ] AWS s3
  - [ ] Azure Blob Storage
  - [ ] Alicloud Object storage
  - [ ] Swift
