### ISSUE TITLE
Etcd Snapshot upload timeout

### ISSUE THREAD

**Issue by nikhilsap** [gardener/etcd-backup-restore#48]
While doing performance test on etcd, db crossed 1 gb of data. While taking snapshot of the db, we faced issue. Etcd went in to crashloopbackoff state. 
on RCA, @georgekuruvillak found the issue with the timeout. Snapshot of the larger db size takes lot of time.
Hoping for a code fix.  

/kind/bug

**Comment by swapnilgm** [comment]
Update: 
This issue is fixed temporarily from gardener via https://github.com/gardener/gardener/pull/304. 
Still we need to have more optimisation like multi-part upload with parallelism to reduce time for uploading large snapshots in case of heavy loaded cluster.
