### ISSUE TITLE
[Feature] Add/Remove member from etcd cluster

### ISSUE THREAD

**Issue by aaronfern** [gardener/etcd-backup-restore#488]
**Feature (What you would like to be added):**
Etcd should be able to add a member to the cluster member list as well as be able to remove a member from the cluster member list

**Motivation (Why is this needed?):**
With the push to multi-node etcd, there are operations where we would need to either add entries to the etcd cluster member list or remove entries from the etcd cluster member list

- [x] Member addition - Scaling up a cluster needs that members be added as learners so that they can synchronise data with the master
- [x] Member deletion - Single member restoration in the case of PV corruption needs the corresponding member to be removed from the cluster and re-added 

**Approach/Hint to the implement solution (optional):**
Add a new package `member` that would contain all functionalities related to member manipulation. These are to be used to add or remove members

**Comment by ishan16696** [comment]
closing this issue in favour of: 
scale-up feature : https://github.com/gardener/etcd-backup-restore/pull/487
restoration in case of pvc-corruption : https://github.com/gardener/etcd-backup-restore/pull/509
/close
