### ISSUE TITLE
Update etcd imports and vendor  to github.com/etcd-io/etcd

### ISSUE THREAD

**Issue by swapnilgm** [gardener/etcd-backup-restore#49]
As per [announcment](https://groups.google.com/forum/#!topic/etcd-dev/pPZetu4Y8rs) soon coreos community is moving etcd and other sub-projects to its own GitHub organization.
Reference: https://github.com/coreos/etcd/issues/9965. 
Probably old path will continue to work with github redirection. Still since its recommended lets re-vendor it.

**Comment by shreyas-s-rao** [comment]
The latest tagged version of etcd is 3.3.9 (July 24th), which was released before the migration announcement was made (issue #9965 raised on July 28th). Hence, it does not incorporate the new repo imports yet and trying to vendor this version leads to vendoring of the old repo as well, resulting in object mismatch errors within the code.

It is advisable to wait for version 3.3.10 of etcd for the revendoring to work.

**Comment by msohn** [comment]
when you do the update please also update the link in
https://github.com/gardener/etcd-backup-restore/blob/master/LICENSE.md
to the new repository location

**Comment by shreyas-s-rao** [comment]
Definitely @msohn

**Comment by shreyas-s-rao** [comment]
This issue shall be addressed when updating to etcd version to 3.4.
