### ISSUE TITLE
[Discuss] Having a single etcd container (which includes backup-restore) or keep the status quo

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-backup-restore#557]
# How to categorize this issue?
/kind discussion

## What would you like to be added

This issue only serves as a placeholder where all active contributors can collaborate and discuss the pros and cons of having a single container housing both backup-restore and etcd. 

# Motivation (Why is this needed?)

Due to several factors like (security compliance, increasing complexity of the code etc.), there is a need to undertake a major refactoring for which a separate [epic](https://github.com/gardener/etcd-backup-restore/issues/549) has been created where we will add/track tasks. It was argued if it would also make sense to not have backup-restore as a separate container and have both etcd and backup-restore as part of a single container.

# Enhancement/Implementation Proposal (optional)

The result of this issue will be a decision about isolation level for backup-restore functionalities.

**Comment by unmarshall** [comment]
Backup-restore IMO is an agent for the main etcd container which has the following responsibilities:
* Backup-restore leader sidecar does the following:
  *  Takes regular delta and full snapshots.
  *  Orchestrates a regular defragmentation of the etcd cluster. In future it will also do threshold based defragmentation (see [Issue#556](https://github.com/gardener/etcd-backup-restore/issues/556).
  * Uploads full/delta snapshots to the backup bucket.
* Every backup-restore is also responsible for:
  * Mutating the etcd configuration and providing the same to the main etcd container.
  * Restoration of the main etcd container in case it is not functional.
  * Provides HTTPs endpoints to externally trigger snapshots/defragmentation

The list might not be complete but serves as a starting point for further discussions.

What stands out is its ability to restore main etcd container in case of change in TLS (from http to https), corruption in etcd DB, DB size exceeding a threshold etc. and the ability for the leading sidecar to serve as an orchestrator for defragmentation. Club that with resource isolation using container boundaries makes a case for it to be in a separate container.
However, there are also complexities which are currently there w.r.t ensuring that with every change in leadership in the etcd cluster, there needs to be a transfer of leadership of the backup-sidecar container as well. Currently this has been the source of several issues. Having said that complexity can be reduced and determinism (avoidance of race conditions can be reduced) can be increased in other ways as well so this alone is not a strong point to move it to a single container.

Please add additional points.

**Comment by unmarshall** [comment]
>Can we also consider in this discussion, the design where a single backup-restore pod operates on multiple etcd member pods? Meaning, etcd-backup-restore is no longer deployed as a sidecar for each etcd member, but rather as a separate single pod which has visibility of all the etcd members and fetches health and metrics from every etcd member.

We already have such an actor `etcd-druid` which today serves as an orchestrator for a few things concerning etcd. Do we need yet another actor? Looking at the above list of pros and cons with multi-zonal deployments this would surely present more challenges making it difficult to restore individual etcd pods.

**Comment by timuthy** [comment]
IIUC, having everything in one container means that `etcd-backup-restore` becomes the process managed of `etcd`. 

Some doubts:
- Availability of `etcd` depends on `etcd-backup-restore`, any runtime failure in `etcd-backup-restore` directly affects the availability of this `etcd` member. Esp. critical for single-node `etcd`s.
- Not ideal for observability as there is no out-of-the-box distinction between the two components.

The complexities in https://github.com/gardener/etcd-backup-restore/issues/557#issuecomment-1319531817 are valid, however I cannot imagine how having a single container will notably simplify the implementation. Instead, additional complexity is added by this kind of "etcd process management" it would need.

Ideally, more details are provided about solving the outlined problems with the single-container approach.

**Comment by ishan16696** [comment]
Everything in one container means we are coupling the health of backup-restore and etcd together, health of 1 process will affect the health of other, vice-versa. This doesn’t seems promising to me untill it solves some major issues/complexity.

**Comment by ishan16696** [comment]
As a conclusion, this design will introduce some complexities/disadvantages like mentioned in comments: https://github.com/gardener/etcd-backup-restore/issues/557#issuecomment-1319653434 and https://github.com/gardener/etcd-backup-restore/issues/557#issuecomment-1319659921.
For now I'm closing this issue but feel free to open this issue if you feel otherwise.
/close
