### ISSUE TITLE
Scheduled full snapshots are not happening after an ETCD container crash

### ISSUE THREAD

**Issue by nikhilsap** [gardener/etcd-backup-restore#62]
While we are doing performance tests in etcd, we noticed after a crash observed in etcd container, it comes up on its own in some time, further we could see the scheduled full snapshots are not being happening or taken.
Full snapshot was scheduled for every 10 mins. Even after 30-40 mins, We could observe there was not even  a single full snapshot. 
I am attaching the backup-restore log file for the
 reference:  [fullsnapshoterror.log](https://github.com/gardener/etcd-backup-restore/files/2534384/fullsnapshoterror.log)

Steps to reproduce : 
1. Delete the etcd container or crash the container 
2. Check the backup-restore  logs, ETCD will come up but scheduled full snapshot is not happening.

**Comment by vlerenc** [comment]
Thank you, that sounds weird and dangerous!

**Comment by swapnilgm** [comment]
Fixed via https://github.com/gardener/etcd-backup-restore/pull/51
