### ISSUE TITLE
[Enhancement] Add tests for the dynamic loading of infrastructure credentials

### ISSUE THREAD

**Issue by renormalize** [gardener/etcd-backup-restore#683]
**Enhancement (What you would like to be added):**
Tests for the dynamic loading of infrastructure credentials.

**Motivation (Why is this needed?):**
Currently, there are no tests of any form which test the dynamic loading of infrastructure credentials. Adding tests for this will enable faster and more confident improvements to the codebase in the future.

**Approach/Hint to the implement solution (optional):**

**Comment by ishan16696** [comment]
closing this issue as tests were added as a part of this PR: https://github.com/gardener/etcd-backup-restore/pull/670
/close
