### ISSUE TITLE
[BUG] Chunk objects get wrongly garbage collected when using openstack swift

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-backup-restore#702]
**Describe the bug:**
Etcd-backup-restore uses multipart uploads for snapshots for all object storage providers, to improve snapshot upload efficiency as well as resilience to network issues. This process involves uploading individual parts, or "chunks", and finally finalizing/composing/completing/committing these individual parts into a single snapshot object on the storage bucket. While most providers recreate the final object from the individual objects on the server side, openstack swift simply expects a 0-byte "manifest object" to be uploaded, which stores the list of names of the individual "segment objects" (chunks) using the same object name as their prefix. Please refer to the [documentation](https://docs.openstack.org/swift/latest/overview_large_objects.html) for more details on this. Please note that in etcd-backup-restore, we use a DLO (dynamic large object), and not an SLO (static large object). The bucket should look something like this:

<img width="1138" alt="not-GCed" src="https://github.com/gardener/etcd-backup-restore/assets/42259948/980c1b2b-599b-4704-997c-09aef5d59df8">

As a contrasting example, GCP's GCS object storage provider creates a new object from the individual chunks, by concatenating those chunks into a single object ([ref](https://cloud.google.com/storage/docs/composite-objects#composing)). This allows for the chunks to be garbage-collected once the object has been "composed", aka finalized.

Hence, etcdbr garbage collector needs to take special care not to delete the chunks for openstack swift provider. Recently a PR #673 was merged, which implemented chunk garbage collection for both GCP and openstack. While it was necessary for GCP, it was not required for openstack, due to the reasons mentioned above. This has caused a regression in copy subcommand, where the manifest object existed for certain snapshots, but the segments were gone due to GC, as can be seen from the below screenshot.

<img width="1138" alt="GCed" src="https://github.com/gardener/etcd-backup-restore/assets/42259948/13fe070d-ca6e-41c4-8103-64d3acc29068">

If chunks should not be garbage collected anymore, then who will clean up those chunks later? Regular deletion of the snapshot object would simply delete the manifest object, but not the segments/chunks. Since the object is a DLO, we cannot use the query parameter `multipart-manifest=delete` for the DELETE API call to swift, since that is allowed only for an SLO type object. Thus, we need to additionally take care of removing the segment objects as well when deleting the snapshot object.

**Expected behavior:**
In the case of openstack swift, chunks should be deleted only during deletion of the main snapshot object, and should never be garbage-collected by themselves.

**How To Reproduce (as minimally and precisely as possible):**
- create openstack swift bucket
- run etcdbr (with garbage collection mode `LimitBased`) to create the following snapshots in this order: full, delta, delta, full
- wait for GC to run (use small GC period to let it run quicker): you should observe the segment/chunks for the 2 delta snapshots being deleted, but the manifest objects remain

/cc @plkokanov 

**Environment (please complete the following information):**
 - Etcd version/commit ID : 
 - Etcd-backup-restore version/commit ID: v0.27.0 and v0.24.7
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: Swift

**Comment by ishan16696** [comment]
Thanks @shreyas-s-rao for detailed explanation of bug but I still have some doubts.
AFAIU, In this PR: https://github.com/gardener/etcd-backup-restore/pull/673 snapshots chunks are deleted( or garbage collected) only when garbage collector runs and CPM components triggers on-demand full-snapshot before starting control plane migration. So, IMO most of the time chunks of full-snapshot must be in bucket and openstack will able to merge these individual parts into a single snapshot object on the storage bucket.
Problem can occur only when garbage collector and CPM's on-demand full-snapshot uploads both getting executed at the same time(or just one after other) can cause this issue and that's the kind of rare and edge case.
Is that's the case ?

**Comment by shreyas-s-rao** [comment]
For CPM, the issue was that the copy of the final full snapshot succeeded, but the copy of the delta snapshots failed. The copy job copies all available snapshots in the bucket, unless we limit this using `etcdcopybackupstask.spec.maxBackups` field. So the issue is not for the final full snapshot, but for the other snapshots.

More importantly, with the delta snapshots' segments gone from the bucket, restoration from such a bucket will fail. We need to quickly merge the fix for this, and release a patch quickly too.

**Comment by ishan16696** [comment]
I'm still not getting properly.
AFAIU, CPM first bring down api-server, so no more data can come to etcd, then it triggers the on-demand final-full-snapshot.
If full-snapshot is available in bucket then there shouldn't be a requirement of any delta snapshot for restoration for bringing up the new etcd as bucket have full-snapshot.

**Comment by ishan16696** [comment]
> but the copy of the delta snapshots failed

If copy of delta failed, and if we have final-full-snapshot which was taken after those delta then we can just delete those delta snapshots from buckets.

**Comment by shreyas-s-rao** [comment]
We can ignore all other snapshots and only copy over the final full snapshot, only if `--max-backups=1`. If not, copy job copies all the snapshots from source to target bucket. In gardener case, this is due to compliance reasons, since we need to retain the last X snapshots or the snapshots for the last X days/weeks, so as to not violate compliance checks.

**Comment by ishan16696** [comment]
ok, got it .. thanks
