### ISSUE TITLE
[Enhancement] Unit tests for OpenStack Swift `snapstore` should mimic the behavior of Dynamic Large Objects

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-backup-restore#705]
**Enhancement (What you would like to be added):**
Unit tests for openstack swift snapstore should consider Dynamic Large Objects

**Motivation (Why is this needed?):**
As mentioned in #702 , etcd-backup-restore uploads snapshots to openstack swift buckets as [DLOs (Dynamic Large Objects)](https://docs.openstack.org/swift/latest/overview_large_objects.html#dynamic-large-objects). The handling of chunks (segments) for such objects is different from multi-part uploaded objects in other storage providers, since chunks can be deleted without affecting the snapshot object, and vice versa. Whereas, in openstack swift, without the chunks, the manifest object is rendered useless, and restoration/copy operations would fail if a snapshot is missing its chunks.

While #703 fixes a regression in the handling of these chunks, the unit tests need to be adapted to consider such DLOs. The PR simply introduces a `deleteChunksForObject` bool field in the swift snapstore struct to circumvent the handling of DLOs in the unit tests, but this is not enough. The unit tests need to mock the actual behavior of the real snapstore, as closely as possible.

**Approach/Hint to the implement solution (optional):**
The unit tests use a mock swift client, which responds to different requests like GET, PUT, DELETE, etc. These handlers for these operations operate on a simple map called `objectsMap`, which stores the object names and their contents. The following changes need to be made to the handlers:
- A `snapstore.Save()` (PUT op) operation would simply write one single object to this `objectsMap`, whereas it is supposed to write to objects:
  1. the segment object, suffixed with `/00000001`, whose contents is the actual snapshot contents
  2. the manifest object, with the actual snapshot name, with contents being empty, since the manifest object is a 0-byte object

- The `snapstore.Delete()` (DELETE op) should now delete both the segment object as well as the manifest object from the `objectsMap`.

- The `snapstore.Fetch()` (GET op) on a snapshot should return a snapshot object that contains the content from the associated segment object, but named after the snapshot (manifest) object.

**Comment by renormalize** [comment]
Thanks @shreyas-s-rao for the detailed approach to the implementation to solve the issue.
PTAL at #710 whenever possible.
