### ISSUE TITLE
[Enhancement] don't stop the loop on temp error

### ISSUE THREAD

**Issue by kayrus** [gardener/etcd-backup-restore#706]
**Enhancement (What you would like to be added):**

the backup process must not be stopped on temp errors (e.g. http, dns, etc. timeout):

https://github.com/gardener/etcd-backup-restore/blob/bdc4f2d50a43b3740f55728cf1b84d7f234fa2a9/pkg/snapshot/snapshotter/snapshotter.go#L296
https://github.com/gardener/etcd-backup-restore/blob/bdc4f2d50a43b3740f55728cf1b84d7f234fa2a9/pkg/snapshot/snapshotter/snapshotter.go#L420

**Motivation (Why is this needed?):**

sometimes the object storage endpoint can have issues due to network hiccups or other temporary issue, this must not stop the backup loop. otherwise there is a high chance to loose the precious backup on a real failure.

**Approach/Hint to the implement solution (optional):**

Temp timeout errors must be detected and logged as a warning, instead of stopping the whole backup loop.

Another approach is to retry inside the transport RoundTripper.

See also https://github.com/golang/go/issues/45729

**Comment by ishan16696** [comment]
Hi @kayrus ,
The backup-restore process actual snapshotter loop, which is responsible for taking backups and starting snapshotter, operates continuously. If an error occurs during the backup process, it doesn't halt the operation. Instead, it employs a backoff mechanism to keep retry taking a snapshot with probing the health of etcd.
 https://github.com/gardener/etcd-backup-restore/blob/727e957b79b38cec83956b392f22c12a953d3c9a/pkg/server/backuprestoreserver.go#L343-L484

**Note**: Above will only true if you are using `etcdbrctl` with `server` command.
```
  server      start the http server with backup scheduler.
```
Please refer here: https://github.com/gardener/etcd-backup-restore/blob/master/docs/deployment/getting_started.md#etcdbrctl-server

**Comment by kayrus** [comment]
I'm using v0.15.4 and I don't see the `Backoff time:` message in logs, while the config contains the following values:

```yaml
exponentialBackoffConfig:
  attemptLimit: 6
  multiplier: 2
  thresholdTime: 2m8s
```

**Comment by kayrus** [comment]
UPD: In my case the `Taking delta snapshot failed: failed uploading manifest for snapshot with error` error occurs and nothing happens since then.

**Comment by ishan16696** [comment]
are you running backup-restore with server sub-command or with snapshot sub-command ?

**Comment by ishan16696** [comment]
> I'm using v0.15.4

It's very old version, I recommend you to consider upgrading the backup-restore or if you are using with [etcd-druid](https://github.com/gardener/etcd-druid) then upgrade the druid version and etcd-druid will take care of upgrading the backup-restore version.

**Comment by kayrus** [comment]
> are you running backup-restore with server sub-command or with snapshot sub-command ?

yes

> I recommend you to consider upgrading the backup-restore

are there any breaking changes with a config or other behaviors?

**Comment by renormalize** [comment]
The only breaking change introduced after *v0.15.4* was dropping the feature of being able to pass cloud storage credentials as environment variables to `etcd-backup-restore` in *v0.19.0*. In the consequent releases, storage credentials are to be passed by using *files mounted* to the `etcd-backup-restore` container where the file path is set to the corresponding provider environment variable. 

Please see #493 for a better understanding about this breaking change.

To get a more holistic understanding of changes and features introduced in releases after *v0.15.4*, please take a look at the `[OPERATOR]` section in the release notes.

**Comment by renormalize** [comment]
Usage of the `server` sub-command on newer versions of `etcd-backup-restore` is recommended to avoid the error observed, as *v0.15.4* is not supported anymore.

Closing this issue @kayrus. Feel free to open an issue in case of any questions/suggestions you have for `etcd-backup-restore` in the future!

**Comment by kayrus** [comment]
Thanks for your answers. I'm closing the issue.
