### ISSUE TITLE
Improve DB file verification time

### ISSUE THREAD

**Issue by swapnilgm** [gardener/etcd-backup-restore#71]
As the etcd DB size grows to around ~1GB, DB file validation takes time in 3-5 minutes. Need to analyse this; and improve the time for verification of DB file. Also, check the effect of IOPS on time as well.

__Environment__:
Etcd version: 3.3.10
Etcd-backup-restore version: 0.3.1

**Comment by amshuman-kr** [comment]
Worst-case, we might want to rethink whether we need to validate on every restart.

**Comment by vlerenc** [comment]
Right, that was what I was thinking/fearing as well. If it cannot be avoided, maybe we can skip it at least when etcd was properly shut down (where it is the least likely that something breaks), which would speed up regular scenarios significantly, e.g. when the control plane is updated or the seed is rolled. That should actually be possible to implement: Write a marker and keep it unless the process stops regularly; then validate only if marker is still on disk when starting the etcd?

**Comment by amshuman-kr** [comment]
If I am not mistaken, we already found that the time taken for verification is proportionate to the size of the database.

So, from my perspective, trying to optimize the actual verification process is just delaying the inevitable.

Only workable long term solution is to avoid unnecessary verification.

**Comment by georgekuruvillak** [comment]
We should do a sanity check(#67). Then start etcd if it passes. On etcd crash, we can try to perform a data validation check and then do a restore if needed. Basically inverting the flow we have at the moment.
