### ISSUE TITLE
[Feature] Docker image with shell access

### ISSUE THREAD

**Issue by jeremych1000** [gardener/etcd-backup-restore#773]
**Feature (What you would like to be added):**
Docker image with shell access, I currently cannot shell into the pod in Kubernetes.

**Motivation (Why is this needed?):**
I am following https://github.com/gardener/etcd-backup-restore/blob/master/docs/operations/manual_restoration.md but it mentions to `curl http://localhost:8080/initialization/status` - I'm guessing I do this inside the etcd-backup-restore pod?

The current dockerfile uses a distroless image which means there is no shell.

**Approach/Hint to the implement solution (optional):**
Have a etcdbrctl-debug image that has a shell.

**Comment by Mounik-tech** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by jeremych1000** [comment]
> try this https://gofile.io/d/Lji8KD select the desired compiler in the installer

That was a suspiciously fast reply - how is gofile relevant?

**Comment by ishan16696** [comment]
Hi @jeremych1000 ,
> Docker image with shell access, I currently cannot shell into the pod in Kubernetes.

Right now, we maintained 2 version of `etcd-backup-restore` : with distroless base image and without distroless base image.
i) For without distroless base image(alpine base image): you can use backup-restore `v0.24.10` and you can shell into the k8s pods but we won't recommend you to use this method as sooner or later we will stop supporting this.
ii ) For distroless base image: you have to use [ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) and attached to the pod.
```
k debug -it pod/etcd-main-0 --image <debugContainerImage>
``` 

> I am following https://github.com/gardener/etcd-backup-restore/blob/master/docs/operations/manual_restoration.md but it mentions to curl http://localhost:8080/initialization/status - I'm guessing I do this inside the etcd-backup-restore pod?

if you are just testing it out then yes, someone have to send `initialization` request to etcd-backup-restore. But in general, you don't have to do all these stuff manually, we take care of all these: from taking backups to validation of data-dir to restoration of etcd if found corrupted. We deploy https://github.com/gardener/etcd-wrapper with etcd-backup-restore as sidecar.

You can use `etcd-druid` aka etcd-operator https://github.com/gardener/etcd-druid which will deploy etcd and etcd-backup-restore. 
you can use this as starting point: https://github.com/gardener/etcd-druid?tab=readme-ov-file#start-using-or-developing-etcd-druid-locally

**Comment by jeremych1000** [comment]
Thanks. I'm currently using `etcd-backup-restore` only for backups/restore; we already have `etcd` provisioned when we started the cluster, so no `etcd-druid`.

I've successfully `curl`-ed the pod, and it returns this:
```
bash-4.4$ curl 10.255.1.228:8080/config               
(^ above command returned nothing)

bash-4.4$ curl 10.255.1.228:8080/initialization/status
New
```

What does new mean here? Is there more detail on what I should expect the `initialisation/status` and `initialization/start` commands to return?

I think it's expected? (https://github.com/gardener/etcd-custom-image/blob/master/etcd_bootstrap_script.sh#L50)

**Comment by ishan16696** [comment]
Hi @jeremych1000 ,
`initialisation/status` is to check the `status` of initialization of etcd's data-dir.
`initialization/start` is to start the initialization process of etcd's data-dir. To check whether etcd's data-dir is corrupted or not, if found corrupted then status reflects the status of restoration. You can refer to this workflow diagram: https://github.com/gardener/etcd-backup-restore/blob/master/docs/proposals/design.md#workflow, although this is quite old but still relevant to what you are asking.

**Comment by ishan16696** [comment]
> What if my entire cluster dies and I lose access to the etcd-backup-restore pod ?  Do I then have to ssh to the underlying node, and exec into the container that way? 

We run etcd-backup-restore as sidecar inside etcd pod, and I would recommend  you to deploy etcd as statefulset. so whenever etcd pod comes back, backup-restore will performs validation check on data-dir if found corrupted then it will trigger the restoration.

> I presume I should have anti affinity rules to make sure they run on different nodes.

yes, I would suggest you to run etcd on dedicated nodes:
1. So that other workloads won't affect the running etcd pods.
2. Etcd's is seems to be very memory consuming database, if they are running on separate nodes then more memory will be available for etcd.
And to bring down this memory consumption, trigger defragmentation periodically, which is also taken care by etcd-backup-restore, you just have to configure it.

> Is the snapshot/backup format the same as etcd's official snapshot? I've downloaded the snapshots etcd-backup-restore makes - it seems to be a tar file which, when decompressed, SEEMS to be the same format?

yes, it's same. Backup-restore just do the compression while uploading the snapshot to backup bucket and decompress them while restoration and compression is configurable.

> We use the full+incremental snapshots. Is there any way of applying the incremental snapshots myself? Like, can I download the latest full snapshot, and latest incremental, and then run some command to merge them?

yeah, you also can do that. You just have to point out the backup-restore to bucket where your backups are present then trigger the restoration then etcd-backup-restore will start restoring from backup at your given path. Once restoration is done then you can trigger a full snapshot and upload that full snapshot to bucket, so next restoration will use this latest full snapshot. Infact, backup-restore provide a way for doing it with our `compact` sub-command, you can run this `compact` subcommand as `k8s job`.
https://github.com/gardener/etcd-druid/blob/master/docs/proposals/02-snapshot-compaction.md
```
  compact     compacts multiple incremental snapshots in etcd backup into a single full snapshot
```

**Comment by jeremych1000** [comment]
>  Infact, backup-restore provide a way for doing it with our compact sub-command, you can run this compact subcommand as k8s job.
https://github.com/gardener/etcd-druid/blob/master/docs/proposals/02-snapshot-compaction.md

That is exactly what I want. Is it possible to run this outside of Kubernetes though? Like, again going back to an entire cluster failure of apiserver + etcd, I would need to compact the snapshots outside of the cluster, and then restore into the cluster.

**Comment by ishan16696** [comment]
yes, you can do that. Just somebody have to trigger this `compact` subcommand with correct configuration.
`compact` sub-command should have access to the cloud container storage where your snapshots (full + incremental snapshots) are residing. `compact` command will start embedded etcd, trigger the restoration using snapshots present in bucket, once the restoration get completed then it triggers a full-snapshot on embedded etcd and upload this new compacted full-snapshot to the same bucket.

**Comment by ishan16696** [comment]
@jeremych1000 can we close this issue ?

**Comment by jeremych1000** [comment]
Yes thanks closed
