### ISSUE TITLE
High memory consumption by etcd backup during full snapshots

### ISSUE THREAD

**Issue by PoojaGidaveer** [gardener/etcd-backup-restore#95]
During load test on etcd, when the full snapshot happens, where full snapshot interval was set to 10mins and delta snapshot interval was set to 5mins, memory consumption by etcd backup sidecar was too high and shoots up after subsequent backup. 

Our Observation - Just for taking backup of 250mb of db size, etcd backup sidecar is consuming 2GB of memory whereas etcd consumes 475mb of memory.

From the heap profile,  we could see that the "Unmarshal" function is consuming high memory which can be seen from below,

![image](https://user-images.githubusercontent.com/33653955/51385543-9a7baa80-1b45-11e9-877e-4303d09f093e.png)

**Comment by nikhilsap** [comment]
We did a performance test where backup sidecar takes only full snapshot. 
we were able to see a sudden rise in memory consumption of backup side car during the full snapshot.

![image](https://user-images.githubusercontent.com/41104107/51901080-d7b12980-23dc-11e9-9b62-f76783f0852b.png)

Here we have trigger load around 19:57 for 1 gb of DB size. We can see that during full snapshot at 20.00 , there is a sudden rise in Backup Memory usage.

**Comment by PadmaB** [comment]
Quite some memory optimizations are done with respect to delta & full snapshots mechanisms.
However, there is still some scope for improvement in case larger volumes of etcd. This can be tracked via a separate issue [#152](https://github.com/gardener/etcd-backup-restore/issues/152)
