### ISSUE TITLE
Raise appropriate alerts based on the backup-restore metrics

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#97]
# Story
As a provider I want timely alerts raised based on the backup&restore metrics to take informed decisions

# Motivation
- A number of metrics are exposed to improve the monitoring of backup-restore functionality #66  
- Defining some alerts based on the metrics will help the Ops to react in a timely manner, in case of any action required - for example missing backups or corrupt/restored etcd

# Acceptance Criteria
Define alerts for 
- [x] a backup is missed
- [ ] corrupt/restored etcd 

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?

**Comment by shreyas-s-rao** [comment]
Re-opening issue to address alerts for failed restores.
